### ISSUE TITLE
Non Ascii Characters request fails

### ISSUE THREAD

**Issue by insomnyawolf** [insomnyawolf/AkiraServerV3#2]
```thread '<unnamed>' panicked at 'index out of bounds: the len is 8 but the index is 8', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::rust_begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:312
   9: core::panicking::panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:85
  10: core::panicking::panic_bounds_check
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:61
  11: core::slice::{{impl}}::index<str*>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539
  12: core::slice::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2396
  13: alloc::vec::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\liballoc\vec.rs:1677
  14: akira_server_v3::request::Client::parse
             at .\src\request.rs:55
  15: akira_server_v3::request::Request::parse
             at .\src\request.rs:18
  16: akira_server_v3::handle_connection
             at .\src\main.rs:86
  17: akira_server_v3::server::{{closure}}
             at .\src\main.rs:73
  18: threadpool::{{impl}}::call_box<closure>
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:95
  19: threadpool::spawn_in_pool::{{closure}}
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:767
thread '<unnamed>' panicked at 'index out of bounds: the len is 9 but the index is 9', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::rust_begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:312
   9: core::panicking::panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:85
  10: core::panicking::panic_bounds_check
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:61
  11: core::slice::{{impl}}::index<str*>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539
  12: core::slice::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2396
  13: alloc::vec::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\liballoc\vec.rs:1677
  14: akira_server_v3::request::Client::parse
             at .\src\request.rs:56
  15: akira_server_v3::request::Request::parse
             at .\src\request.rs:18
  16: akira_server_v3::handle_connection
             at .\src\main.rs:86
  17: akira_server_v3::server::{{closure}}
             at .\src\main.rs:73
  18: threadpool::{{impl}}::call_box<closure>
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:95
  19: threadpool::spawn_in_pool::{{closure}}
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:767
thread '<unnamed>' panicked at 'index out of bounds: the len is 9 but the index is 9', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::rust_begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:312
   9: core::panicking::panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:85
  10: core::panicking::panic_bounds_check
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:61
  11: core::slice::{{impl}}::index<str*>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539
  12: core::slice::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2396
  13: alloc::vec::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\liballoc\vec.rs:1677
  14: akira_server_v3::request::Client::parse
             at .\src\request.rs:56
  15: akira_server_v3::request::Request::parse
             at .\src\request.rs:18
  16: akira_server_v3::handle_connection
             at .\src\main.rs:86
  17: akira_server_v3::server::{{closure}}
             at .\src\main.rs:73
  18: threadpool::{{impl}}::call_box<closure>
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:95
  19: threadpool::spawn_in_pool::{{closure}}
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:767
thread '<unnamed>' panicked at 'index out of bounds: the len is 9 but the index is 9', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::rust_begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:312
   9: core::panicking::panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:85
  10: core::panicking::panic_bounds_check
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:61
  11: core::slice::{{impl}}::index<str*>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539
  12: core::slice::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2396
  13: alloc::vec::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\liballoc\vec.rs:1677
  14: akira_server_v3::request::Client::parse
             at .\src\request.rs:56
  15: akira_server_v3::request::Request::parse
             at .\src\request.rs:18
  16: akira_server_v3::handle_connection
             at .\src\main.rs:86
  17: akira_server_v3::server::{{closure}}
             at .\src\main.rs:73
  18: threadpool::{{impl}}::call_box<closure>
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:95
  19: threadpool::spawn_in_pool::{{closure}}
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:767
thread '<unnamed>' panicked at 'index out of bounds: the len is 9 but the index is 9', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::rust_begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:312
   9: core::panicking::panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:85
  10: core::panicking::panic_bounds_check
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:61
  11: core::slice::{{impl}}::index<str*>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539
  12: core::slice::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2396
  13: alloc::vec::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\liballoc\vec.rs:1677
  14: akira_server_v3::request::Client::parse
             at .\src\request.rs:56
  15: akira_server_v3::request::Request::parse
             at .\src\request.rs:18
  16: akira_server_v3::handle_connection
             at .\src\main.rs:86
  17: akira_server_v3::server::{{closure}}
             at .\src\main.rs:73
  18: threadpool::{{impl}}::call_box<closure>
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:95
  19: threadpool::spawn_in_pool::{{closure}}
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:767
```

**Comment by insomnyawolf** [comment]
half of the problem was how did i parsed the client strings, i need to really work on it.

Now im facing that issue:
```Request { method: "GET", path: "/アーティスト - 美咲ゆう/", client: Client { client: "HTTP/1.1\r\nHost: 127.0.0.1:8080\r\nConnection: keep-alive\r\nCache-Control: max-age=0\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\r\nReferer: http://127.0.0.1:8080/\r\nAccept" } }
M:/pic/アーティスト - 美咲ゆう/
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::rust_begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:312
   9: core::panicking::panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:85
  10: core::panicking::panic_bounds_check
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:61
  11: core::slice::{{impl}}::index<str*>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2539
  12: core::slice::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\slice\mod.rs:2396
  13: alloc::vec::{{impl}}::index<str*,usize>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\liballoc\vec.rs:1677
  14: akira_server_v3::request::Request::parse
             at .\src\request.rs:16
  15: akira_server_v3::handle_connection
             at .\src\main.rs:85
  16: akira_server_v3::server::{{closure}}
             at .\src\main.rs:72
  17: threadpool::{{impl}}::call_box<closure>
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:95
  18: threadpool::spawn_in_pool::{{closure}}
             at C:\Users\iw\.cargo\registry\src\github.com-1ecc6299db9ec823\threadpool-1.7.1\src\lib.rs:767
```

**Comment by insomnyawolf** [comment]
Looks Like It's Fixed
